FROM node:18 AS builder

WORKDIR /app

COPY . .

RUN npm install -g pnpm
RUN pnpm install
RUN node build

FROM nginx:stable-alpine3.20-slim

RUN apk update && apk upgrade --no-cache

COPY --from=builder /app/public /usr/share/nginx/html
